### ISSUE TITLE
Add API documentation [3pt]

### ISSUE THREAD

**Issue by shasherazi** [monicah79/Final-capstone-backend#17]
Use `rswagger` to generate API docs

**Comment by kapuranirudh** [comment]
Hi,

I would do that for u, can u share the details.

Thanks

**Comment by shasherazi** [comment]
Hi @kapuranirudh, thank you for your offer. Actually, this is a capstone project for our bootcamp, so we can't accept contributions from anyone outside the team.

**Comment by kapuranirudh** [comment]
Okay no problem..!!
